const express = require('express')
const multer = require('multer')
const uuid = require('uuid').v4

const storage = multer.diskStorage({
    destination:(req,file,cb)=>{
        cb(null,'uploads')
    },
    filename:(req,file,cb)=>{
        const {originalname} = file
        cb(null, `${uuid()}-${originalname}`)  // saving the original file name and extension prefixed by uniqe ID generated by the UUID module
    }
})
const upload = multer({storage});

const app = express()
app.use(express.static('public')); // the folder that we use

app.post('/upload',upload.array('video'),(req,res)=>{  
    return res.json({status:'OK', uploaded:req.files.length});
})

app.listen(3000, ()=>console.log('App is listening...'))

